url_dictionary = {'7-МИ 11-ТИ КИЛОМЕТЪР': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5p3y&f1=',
                  'АБДОВИЦА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5p66&f1=',
                  'БАНИШОРА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5p88&f1=',
                  'БЕЛИТЕ БРЕЗИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5p9f&f1=',
                  'БЕНКОВСКИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5pal&f1=',
                  'БОРОВО': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5pbm&f1=',
                  'БОТУНЕЦ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5rpq&f1=',
                  'БОТУНЕЦ 2': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5rzw&f1=',
                  'БОЯНА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5s1n&f1=',
                  'БЪКСТОН': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5s37&f1=',
                  'ВИТОША': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5s5g&f1=',
                  'ВОЕННА РАМПА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5s76&f1=',
                  'ВРАЖДЕБНА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5saj&f1=',
                  'ВРЪБНИЦА 1': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5sc3&f1=',
                  'ВРЪБНИЦА 2': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5sf9&f1=',
                  'ГЕВГЕЛИЙСКИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5shh&f1=',
                  'ГЕО МИЛЕВ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5siy&f1=',
                  'ГОРНА БАНЯ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5skl&f1=',
                  'ГОРУБЛЯНЕ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5sm6&f1=',
                  'ГОЦЕ ДЕЛЧЕВ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5we3&f1=',
                  'ГРАДИНА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wgl&f1=',
                  'ДИАНАБАД': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wj1&f1=',
                  'ДИМИТЪР МИЛЕНКОВ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wkq&f1=',
                  'ДОКТОРСКИ ПАМЕТНИК': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wov&f1=',
                  'ДРАГАЛЕВЦИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wr6&f1=',
                  'ДРУЖБА 1': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wtj&f1=',
                  'ДРУЖБА 2': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5wwl&f1=',
                  'ДЪРВЕНИЦА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5x16&f1=',
                  'ЗАПАДЕН ПАРК': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5x60&f1=',
                  'ЗАХАРНА ФАБРИКА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5x8c&f1=',
                  'ЗОНА Б-18': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5xab&f1=',
                  'ЗОНА Б-19': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5xc4&f1=',
                  'ЗОНА Б-5': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5xdg&f1=',
                  'ЗОНА Б-5-3': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5xei&f1=',
                  'ИВАН ВАЗОВ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yl1&f1=',
                  'ИЗГРЕВ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yox&f1=',
                  'ИЗТОК': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yq1&f1=',
                  'ИЛИНДЕН': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yru&f1=',
                  'ИЛИЯНЦИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yt9&f1=',
                  'КАРПУЗИЦА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yug&f1=',
                  'КНЯЖЕВО': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yvz&f1=',
                  'КРАСНА ПОЛЯНА 1': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yxd&f1=',
                  'КРАСНА ПОЛЯНА 2': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5yyn&f1=',
                  'КРАСНА ПОЛЯНА 3': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5z0l&f1=',
                  'КРАСНО СЕЛО': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5z2m&f1=',
                  'КРЕМИКОВЦИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5z68&f1=',
                  'КРЪСТОВА ВАДА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5z7l&f1=',
                  'ЛАГЕРА': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5z8x&f1=',
                  'ЛЕВСКИ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5za5&f1=',
                  'ЛЕВСКИ В': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zbh&f1=',
                  'ЛЕВСКИ Г': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zdj&f1=',
                  'ЛОЗЕНЕЦ': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zgp&f1=',
                  'ЛЮЛИН - ЦЕНТЪР': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zia&f1=',
                  'ЛЮЛИН 1': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zm7&f1=',
                  'ЛЮЛИН 2': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zpt&f1=',
                  'ЛЮЛИН 3': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zqn&f1=',
                  'ЛЮЛИН 4': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zrz&f1=',
                  'ЛЮЛИН 5': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zsv&f1=',
                  'ЛЮЛИН 6': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zus&f1=',
                  'ЛЮЛИН 7': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zwd&f1=',
                  'ЛЮЛИН 8': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zy1&f1=',
                  'ЛЮЛИН 9': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n5zz7&f1=',
                  'ЛЮЛИН 10': 'https://www.imot.bg/pcgi/imot.cgi?act=3&slink=6n6003&f1=',
                  }
